<script lang="ts">
	import type { AnalysisResult } from '$lib/types.js';

	let {
		result,
		onNext,
		onBack
	}: {
		result: AnalysisResult;
		onNext: () => void;
		onBack: () => void;
	} = $props();

	const maxCitations = $derived(
		result.paragraphs.length > 0
			? Math.max(...result.paragraphs.map((p) => p.citationCount), 1)
			: 1
	);


	const CATEGORY_LABELS: Record<string, string> = {
		epistemic_generalization: 'Epistemic generalisation',
		statistical_claim: 'Statistical claim',
		attribution: 'Attribution',
		causal_claim: 'Causal claim',
		consensus_claim: 'Consensus claim'
	};

	const FORMAT_LABELS: Record<string, string> = {
		apa: 'APA',
		ieee: 'IEEE',
		mixed: 'Mixed (APA + IEEE)',
		none: 'None detected'
	};

	let expandedParagraphs = $state<Set<number>>(new Set());

	function toggleParagraph(i: number) {
		const next = new Set(expandedParagraphs);
		next.has(i) ? next.delete(i) : next.add(i);
		expandedParagraphs = next;
	}
</script>

<div>
	<h2 class="text-2xl font-bold mb-1" style="font-family: 'Open Sans', sans-serif;">Step 3: Textual Analysis</h2>
	<p class="text-sm text-gray-600 mb-8 mt-0" style="font-family: 'Merriweather', serif;">
		Results are generated by a dataset-driven classifier. They are indicative, not conclusive. Review each flag carefully.
	</p>

	<!-- Summary cards -->
	<div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
		<div class="border-2 border-black p-4 rounded-sm text-center">
			<div class="text-3xl font-bold" style="font-family: 'Open Sans', sans-serif;">{result.totalCitations}</div>
			<div class="text-xs text-gray-600 mt-1" style="font-family: 'Open Sans', sans-serif;">Citations found</div>
		</div>
		<div class="border-2 border-black p-4 rounded-sm text-center">
			<div class="text-3xl font-bold" style="font-family: 'Open Sans', sans-serif;">{result.averageDensity}</div>
			<div class="text-xs text-gray-600 mt-1" style="font-family: 'Open Sans', sans-serif;">Avg per paragraph</div>
		</div>
		<div class="border-2 border-black p-4 rounded-sm text-center">
			<div class="text-3xl font-bold" style="font-family: 'Open Sans', sans-serif; color: {result.totalFlaggedClaims > 0 ? '#C00A35' : '#24A793'};">
				{result.totalFlaggedClaims}
			</div>
			<div class="text-xs text-gray-600 mt-1" style="font-family: 'Open Sans', sans-serif;">Flagged claims</div>
		</div>
		<div class="border-2 border-black p-4 rounded-sm text-center">
			<div class="text-xl font-bold mt-1" style="font-family: 'Open Sans', sans-serif;">{FORMAT_LABELS[result.citationFormat]}</div>
			<div class="text-xs text-gray-600 mt-1" style="font-family: 'Open Sans', sans-serif;">Citation format</div>
		</div>
	</div>

	<!-- Citation density table -->
	<h3 class="text-base font-bold mb-3" style="font-family: 'Open Sans', sans-serif;">Citation density by paragraph</h3>
	<div class="border border-gray-200 rounded-sm overflow-hidden mb-8">
		<table class="w-full text-sm border-collapse">
			<thead>
				<tr style="background-color: #f9fafb;">
					<th class="text-left px-4 py-2 font-semibold border-b border-gray-200 w-16" style="font-family: 'Open Sans', sans-serif;">¶</th>
					<th class="text-left px-4 py-2 font-semibold border-b border-gray-200" style="font-family: 'Open Sans', sans-serif;">Paragraph preview</th>
					<th class="text-center px-4 py-2 font-semibold border-b border-gray-200 w-24" style="font-family: 'Open Sans', sans-serif;">Citations</th>
					<th class="text-center px-4 py-2 font-semibold border-b border-gray-200 w-32" style="font-family: 'Open Sans', sans-serif;">Density</th>
					<th class="text-center px-4 py-2 font-semibold border-b border-gray-200 w-24" style="font-family: 'Open Sans', sans-serif;">Flags</th>
				</tr>
			</thead>
			<tbody>
				{#each result.paragraphs as para, i}
					<tr
						class="cursor-pointer hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-b-0"
						style="background-color: {para.isFlagged ? '#fff5f5' : 'transparent'};"
						onclick={() => toggleParagraph(i)}
						aria-expanded={expandedParagraphs.has(i)}
					>
						<td class="px-4 py-3 text-gray-400 font-mono text-xs">{i + 1}</td>
						<td class="px-4 py-3">
							<p class="m-0 text-xs text-gray-700 line-clamp-2" style="font-family: 'Merriweather', serif;">
								{para.text.slice(0, 120)}{para.text.length > 120 ? '…' : ''}
							</p>
							{#if expandedParagraphs.has(i) && para.flaggedClaims.length > 0}
								<div class="mt-3 space-y-2">
									{#each para.flaggedClaims as claim}
										<div class="bg-red-50 border-l-4 border-red-400 p-3 rounded-sm">
											<p class="text-xs font-semibold m-0 mb-1" style="font-family: 'Open Sans', sans-serif; color: #C00A35;">
												{CATEGORY_LABELS[claim.category] ?? claim.category}
												<span class="font-normal ml-2 text-gray-500">score: {(claim.score * 100).toFixed(0)}%</span>
											</p>
											<p class="text-xs m-0 mb-1" style="font-family: 'Merriweather', serif;">{claim.sentence}</p>
											<p class="text-xs text-gray-500 m-0" style="font-family: 'Open Sans', sans-serif;">
												Matched phrases:
												{#each claim.matchedPhrases as phrase, pi}
													<mark class="bg-yellow-200 px-0.5 rounded-sm mx-0.5">{phrase}</mark>{pi < claim.matchedPhrases.length - 1 ? '' : ''}
												{/each}
											</p>
										</div>
									{/each}
								</div>
							{/if}
						</td>
						<td class="px-4 py-3 text-center font-bold" style="font-family: 'Open Sans', sans-serif;">{para.citationCount}</td>
						<td class="px-4 py-3">
							<div class="flex items-center gap-2">
								<div class="flex-1 bg-gray-100 rounded-full h-2 overflow-hidden">
									<div
										class="h-2 rounded-full transition-all"
										style="width: {maxCitations > 0 ? (para.citationCount / maxCitations) * 100 : 0}%; background-color: {para.citationCount === 0 ? '#d1d5db' : '#FFCD00'}; border: {para.citationCount > 0 ? '1px solid #e6b800' : 'none'};"
									></div>
								</div>
							</div>
						</td>
						<td class="px-4 py-3 text-center">
							{#if para.flaggedClaims.length > 0}
								<span class="inline-flex items-center justify-center w-6 h-6 rounded-full text-xs font-bold" style="background-color: #FEE2E2; color: #C00A35; font-family: 'Open Sans', sans-serif;">
									{para.flaggedClaims.length}
								</span>
							{:else}
								<span class="text-green-600 text-sm" aria-label="No flags">✓</span>
							{/if}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>

	{#if result.totalFlaggedClaims > 0}
		<div class="bg-amber-50 border border-amber-200 rounded-sm p-4 mb-8">
			<p class="text-sm font-semibold m-0 mb-1" style="font-family: 'Open Sans', sans-serif;">
				ℹ About flagged claims
			</p>
			<p class="text-sm text-gray-700 m-0" style="font-family: 'Merriweather', serif;">
				Flagged sentences contain phrases commonly associated with claims that require a citation, but no citation was found nearby. This does not mean the claim is wrong; it is an indication to review whether a source should be added. Click on a paragraph row to see the details.
			</p>
		</div>
	{/if}

	<div class="flex justify-between">
		<button
			onclick={onBack}
			type="button"
			class="px-6 py-3 text-sm font-semibold border-2 border-gray-300 hover:border-black transition-colors rounded-sm"
			style="font-family: 'Open Sans', sans-serif;"
		>
			← Back
		</button>
		<button
			onclick={onNext}
			type="button"
			class="px-8 py-3 font-bold text-sm tracking-wide rounded-sm"
			style="font-family: 'Open Sans', sans-serif; background-color: #FFCD00; color: #000;"
		>
			Next: Review Statement →
		</button>
	</div>
</div>
