<script lang="ts">
	// Step 4: the final review and export step
	import type { ComplianceResult } from '$lib/types.js';

	let {
		statement = $bindable(''), // editable by the student directly in the textarea
		compliance,
		onBack,
		onRestart
	}: {
		statement: string;
		compliance: ComplianceResult;
		onBack: () => void;
		onRestart: () => void;
	} = $props();

	// both export buttons are disabled until this is checked
	let approved = $state(false);
	let copyLabel = $state('Copy to clipboard');
	let copied = $state(false);

	async function copyToClipboard() {
		await navigator.clipboard.writeText(statement);
		copied = true;
		copyLabel = 'Copied!';
		setTimeout(() => {
			copied = false;
			copyLabel = 'Copy to clipboard';
		}, 2500);
	}

	function downloadTxt() {
		const blob = new Blob([statement], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'ai-transparency-statement.txt';
		a.click();
		URL.revokeObjectURL(url);
	}
</script>

<div>
	<h2 class="text-2xl font-bold mb-1" style="font-family: 'Open Sans', sans-serif;">Step 4: Review & Export</h2>
	<p class="text-sm text-gray-600 mb-6 mt-0" style="font-family: 'Merriweather', serif;">
		Review the generated statement carefully. You may edit it to ensure it accurately reflects your experience. When satisfied, approve and export.
	</p>

	<!-- Compliance banner -->
	<div
		class="border-l-4 p-4 mb-6 rounded-sm"
		style="
			border-color: {compliance.status === 'compliant' ? '#24A793' : compliance.status === 'no_ai' ? '#5287C6' : '#C00A35'};
			background-color: {compliance.status === 'compliant' ? '#f0fdfb' : compliance.status === 'no_ai' ? '#eff6ff' : '#fff5f5'};
		"
		role="status"
	>
		<p class="font-bold text-sm m-0" style="font-family: 'Open Sans', sans-serif;">
			{#if compliance.status === 'compliant'}
				✓ AI use appears compliant with the selected UU AI Index level
			{:else if compliance.status === 'no_ai'}
				ℹ No AI use was reported
			{:else}
				⚠ Review: reported AI use may exceed the selected UU AI Index level
			{/if}
		</p>
		{#if compliance.violations.length > 0}
			<ul class="m-0 mt-2 pl-4 list-disc space-y-0.5">
				{#each compliance.violations as v}
					<li class="text-xs" style="font-family: 'Open Sans', sans-serif;">{v}</li>
				{/each}
			</ul>
		{/if}
	</div>

	<!-- Editable statement -->
	<div class="mb-4">
		<label for="statement-textarea" class="block text-sm font-semibold mb-2" style="font-family: 'Open Sans', sans-serif;">
			Generated AI Usage Statement <span class="font-normal text-gray-500">(editable)</span>
		</label>
		<textarea
			id="statement-textarea"
			bind:value={statement}
			rows={22}
			class="w-full border-2 border-gray-300 p-4 font-mono text-xs leading-relaxed focus:border-black focus:outline-none resize-y rounded-sm transition-colors"
			spellcheck="false"
		></textarea>
	</div>

	<!-- Disclaimer -->
	<div class="bg-gray-50 border border-gray-200 rounded-sm p-4 mb-6">
		<p class="text-xs text-gray-600 m-0" style="font-family: 'Open Sans', sans-serif;">
			<strong>Important:</strong> This statement was generated by an automated tool based on your self-reported information and a textual analysis of your text. It is a recommendation only. <strong>You are responsible for its accuracy.</strong> By approving, you confirm this statement honestly represents your AI use.
		</p>
	</div>

	<!-- Approval checkbox -->
	<label class="flex items-start gap-3 cursor-pointer mb-8 border-2 p-4 rounded-sm" style="border-color: {approved ? '#000' : '#e5e7eb'}; background-color: {approved ? '#fffbeb' : '#fff'};">
		<input
			type="checkbox"
			bind:checked={approved}
			class="mt-0.5 w-5 h-5 accent-black"
			aria-describedby="approval-hint"
		/>
		<div>
			<span class="font-semibold text-sm" style="font-family: 'Open Sans', sans-serif;">
				I have read and reviewed this statement, and it accurately represents my AI use during the writing process.
			</span>
			<p id="approval-hint" class="text-xs text-gray-500 m-0 mt-1" style="font-family: 'Open Sans', sans-serif;">
				Required before exporting.
			</p>
		</div>
	</label>

	<!-- Export actions -->
	<div class="flex flex-wrap gap-3 mb-8">
		<button
			onclick={copyToClipboard}
			disabled={!approved}
			type="button"
			class="flex items-center gap-2 px-5 py-2.5 font-bold text-sm border-2 border-black transition-colors rounded-sm disabled:opacity-40 disabled:cursor-not-allowed"
			style="font-family: 'Open Sans', sans-serif; background-color: {approved ? '#FFCD00' : '#e5e7eb'}; color: #000;"
		>
			<svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
				<rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
				<path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"></path>
			</svg>
			{copyLabel}
		</button>

		<button
			onclick={downloadTxt}
			disabled={!approved}
			type="button"
			class="flex items-center gap-2 px-5 py-2.5 font-bold text-sm border-2 transition-colors rounded-sm disabled:opacity-40 disabled:cursor-not-allowed"
			style="font-family: 'Open Sans', sans-serif; border-color: {approved ? '#000' : '#e5e7eb'}; background: transparent; color: #000;"
		>
			<svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
				<path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"></path>
			</svg>
			Download .txt
		</button>
	</div>

	<div class="flex justify-between">
		<button
			onclick={onBack}
			type="button"
			class="px-6 py-3 text-sm font-semibold border-2 border-gray-300 hover:border-black transition-colors rounded-sm"
			style="font-family: 'Open Sans', sans-serif;"
		>
			← Back to Analysis
		</button>
		<button
			onclick={onRestart}
			type="button"
			class="px-6 py-3 text-sm font-semibold border-2 border-gray-300 hover:border-black transition-colors rounded-sm"
			style="font-family: 'Open Sans', sans-serif;"
		>
			Analyse another paper
		</button>
	</div>
</div>
